name: test-coverage

permissions:
  contents: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-coverage:
    steps:
    - uses: actions/checkout@v4

    name: Go test coverage check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3

      - name: generate test coverage
        run: go test ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./... -timeout 20m

      - name: check test coverage
        uses: vladopajic/go-test-coverage@v2.13.1
        with:
          config: ./.testcoverage.yml
