name: test-coverage

permissions:
  contents: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-coverage:
    name: Go test coverage check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.24'
          check-latest: true
          cache: false

      - name: Install packages
        run: |
          sudo apt update
          sudo apt upgrade -y
          sudo apt autoremove -y
          sudo apt install -y gcc libgl1-mesa-dev libglu1-mesa xorg-dev libgtk-3-dev libxkbcommon-dev

      - name: Install dependencies
        run: |
          go mod download
          go install -v github.com/fyne-io/fyne-cross@latest

      - name: generate test coverage
        run: go test ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./... -timeout 20m

      - name: check test coverage
        uses: vladopajic/go-test-coverage@f080863892c102695c8066abc08aae12e3e94e1b # v2.13.1
        with:
          config: ./.testcoverage.yml
          git-token: ${{ github.ref_name == 'main' && secrets.GITHUB_TOKEN || '' }}
          git-branch: badges
