name: test-build

permissions:
  contents: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '>=1.24'
        check-latest: true
        cache: false

    - name: Install packages
      run: |
        sudo apt install -y gcc libgl1-mesa-dev libglu1-mesa xorg-dev libgtk-3-dev libxkbcommon-dev

    - name: Install dependencies
      run: |
        go mod download
        go get -u -v fyne.io/fyne/v2@latest
        go install fyne.io/fyne/v2/cmd/fyne@latest
        go install github.com/fyne-io/fyne-cross@latest

    - name: Build
      run: |
        fyne-cross android -arch=arm64
      env:
        CGO_ENABLED: 1
        GOAMD64: v1

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-linux
        path: |
          *.apk
        if-no-files-found: error
        compression-level: 9
