name: test-build-windows

permissions:
  contents: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '>=1.24'
        check-latest: true
        cache: false

    - name: Install dependencies
      run: |
        go mod download
        go install -v github.com/fyne-io/fyne-cross@latest

    - name: Build Windows
      run: |
        fyne-cross windows -arch=amd64
      env:
        CGO_ENABLED: 1

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: TEST-BUILD-DO-NOT-USE-THIS
        path: |
          fyne-cross/dist/windows-amd64/*
        if-no-files-found: error
        compression-level: 9
