name: test-build-ios

permissions:
  contents: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-build-ios:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '>=1.24'
        check-latest: true
        cache: false

    - name: Install dependencies
      run: |
        go mod download
        go install -v fyne.io/fyne/v2/cmd/fyne@latest

    - name: Build iOS
      run: |
        fyne package -os ios -appID io.github.picocrypt.Picocrypt -icon Icon.png
      env:
        CGO_ENABLED: 1

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: TEST-BUILD-DO-NOT-USE-THIS
        path: |
          fyne-cross/dist/ios/*
        if-no-files-found: error
        compression-level: 9
