name: test-build

permissions:
  contents: write

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '>=1.24'
        check-latest: true
        cache: false

    - name: Install packages
      run: |
        sudo apt install -y gcc libgl1-mesa-dev libglu1-mesa xorg-dev libgtk-3-dev libxkbcommon-dev unzip

    - name: Install dependencies
      run: |
        go mod download
        go get -u -v all
        go install -v github.com/fyne-io/fyne-cross@latest

    - name: Build Windows
      run: |
        fyne-cross windows -arch=amd64
      env:
        CGO_ENABLED: 1

    - name: Build Android
      run: |
        fyne-cross android -arch=arm64
      env:
        CGO_ENABLED: 1

    - name: Upload Windows artifacts
      uses: actions/upload-artifact@v4
      with:
        name: test-build-windows
        path: |
          fyne-cross/dist/windows-amd64/*
        if-no-files-found: error
        compression-level: 9

    - name: Upload Android artifacts
      uses: actions/upload-artifact@v4
      with:
        name: test-build-android
        path: |
          fyne-cross/dist/android-arm64/*
        if-no-files-found: error
        compression-level: 9
